import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "@/trpc/react";
import { NotifierProvider } from "./contexts/NotifierContext";
import { Toaster } from "@/components/ui/toaster";
import { Provider } from "jotai";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <NotifierProvider>
            <Provider>{children}</Provider>
          </NotifierProvider>
        </TRPCReactProvider>
        <Toaster />
      </body>
    </html>
  );
}
